language: go

install:
 - echo "install steps are now empty"

script:
 - mkdir -p $GOPATH/bin
 - mkdir -p $GOPATH/pkg
 - echo "GOPATH is $GOPATH"
 - echo "pwd:"
 - pwd
 - echo
 - echo "ls -ltr on $GOPATH:"
 - ls -ltr $GOPATH
 - echo
 - echo "which go:"
 - which go
 - echo
 - go get -v .
 - go test -v .

